services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: schoolschedule
    volumes:
      - d:/docker-data/pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    restart: on-failure
